# Generated by Django 4.0.6 on 2022-07-15 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=64)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('changepublication_date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('TK', 'Tanks'), ('HE', 'Heals'), ('DD', 'DD'), ('MH', 'Merchants'), ('GM', 'Guild Masters'), ('QG', 'Quest Givers'), ('BS', 'Blacksmiths'), ('TN', 'Tanners'), ('PM', 'Potion Makers'), ('SM', 'Spell Masters')], max_length=2)),
                ('rating', models.ImageField(default=0, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['publication_date', '-changepublication_date'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('changepublication_date', models.DateTimeField(auto_now=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='board.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responseUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['publication_date', '-changepublication_date'],
            },
        ),
    ]
