# Generated by Django 4.0.6 on 2022-07-16 16:59

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-publication_date', '-changepublication_date'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AddField(
            model_name='response',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('TK', 'Tanks'), ('HE', 'Heals'), ('DD', 'DD'), ('MH', 'Merchants'), ('GM', 'Guild Masters'), ('QG', 'Quest Givers'), ('BS', 'Blacksmiths'), ('TN', 'Tanners'), ('PM', 'Potion Makers'), ('SM', 'Spell Masters')], max_length=2, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='heading',
            field=models.CharField(max_length=64, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст объявления'),
        ),
        migrations.AlterField(
            model_name='response',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='board.advertisement', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='response',
            name='tekst',
            field=models.TextField(verbose_name='Текст отклика'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responseUser', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
