# Generated by Django 4.0.6 on 2022-07-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
